# Generated by Django 4.2.7 on 2023-12-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='datePosted',
            field=models.DateField(null=True),
        ),
    ]
