# Generated by Django 4.2.7 on 2023-12-16 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocal_requests', '0003_vocalrequest_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocalrequest',
            name='accepted',
        ),
    ]
